# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('auto_model', models.CharField(max_length=50)),
                ('auto_number', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='Branchproduct',
            fields=[
                ('branchproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_rest', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Branch')),
            ],
            options={
                'db_table': 'BranchProduct',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('client_passport', models.CharField(max_length=11)),
                ('client_birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_birthday', models.DateField()),
                ('driver_salary', models.IntegerField()),
                ('driver_recruitment', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Auto')),
            ],
            options={
                'db_table': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=50)),
                ('manager_birthday', models.DateField()),
                ('manager_recruitment', models.DateField()),
                ('manager_salary', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Branch')),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='Orderproduct',
            fields=[
                ('orderproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_count', models.IntegerField()),
            ],
            options={
                'db_table': 'OrderProduct',
            },
        ),
        migrations.CreateModel(
            name='Ordertable',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_address', models.CharField(max_length=100)),
                ('order_totalcost', models.FloatField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Auto')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Manager')),
            ],
            options={
                'db_table': 'OrderTable',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_cost', models.FloatField()),
                ('product_made', models.CharField(max_length=20)),
                ('product_description', models.CharField(blank=True, max_length=100, null=True)),
                ('product_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Ordertable'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Product'),
        ),
        migrations.AddField(
            model_name='branchproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Product'),
        ),
        migrations.AddField(
            model_name='auto',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VStorage.Branch'),
        ),
    ]
