# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VStorage', '0004_manager_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='user_id',
            field=models.OneToOneField(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
