# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VStorage', '0005_auto_20160104_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='user_id',
            new_name='user',
        ),
    ]
