# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VStorage', '0006_auto_20160104_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
    ]
