# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VStorage', '0007_remove_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_passport',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
