# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VStorage', '0008_auto_20160111_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
