# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VStorage', '0011_auto_20160111_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='order_address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
